// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQaKdu7w1FBN21XEXIm-0qMzzFEfKCUJM',
    appId: '1:643063938834:web:189dcd4ec138070422fdcb',
    messagingSenderId: '643063938834',
    projectId: 'grocify-5568c',
    authDomain: 'grocify-5568c.firebaseapp.com',
    storageBucket: 'grocify-5568c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvHwesG5_PpeMHBKWTAYbKbP_rTdcnNNI',
    appId: '1:643063938834:android:4ee0acb19c6c368322fdcb',
    messagingSenderId: '643063938834',
    projectId: 'grocify-5568c',
    storageBucket: 'grocify-5568c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt_0CHS8oIxkvPwCtPaqThMJ1T3Haa2sE',
    appId: '1:643063938834:ios:568e126058751dc422fdcb',
    messagingSenderId: '643063938834',
    projectId: 'grocify-5568c',
    storageBucket: 'grocify-5568c.firebasestorage.app',
    androidClientId: '643063938834-676g844lgl2tfusijtsk1hjnl0640nl1.apps.googleusercontent.com',
    iosClientId: '643063938834-s8cg7802cd8iphpv5g1qprfi7k06860s.apps.googleusercontent.com',
    iosBundleId: 'com.example.grocify',
  );

}